### ISSUE TITLE
Error with redis?

### ISSUE THREAD

**Issue by springjben** [guerrerocarlos/bitcoin-receive-payments#11]
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

Any ideas? I am on Windows running MongoDB on the same port?

**Comment by springjben** [comment]
https://redislabs.com/ebook/appendix-a/a-3-installing-on-windows/a-3-2-installing-redis-on-window/

So I needed to do and run that.

**Comment by gustawdaniel** [comment]
It could be better documented. I propose to allow on configuration of host and port of redis because of it will be easier to use it with docker.
